name: dexkorchatapp
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.1
  emoji_picker_flutter: ^3.0.0
  firebase_messaging: ^15.1.2
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  flutter_notification_channel: ^3.1.0
  gallery_saver_updated: ^3.0.0
  lottie: ^3.1.2
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  

